<?php

namespace FollowMe\Bundle\ModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    /**
     * @param $name
     * @return boolean TRUE if the name is already used, FALSE otherwise
     */
    public function nameAlreadyUsed($name) {
        $result = $this->findOneBy(array(
            'name' => $name
        ));

        return ($result != null);
    }

}
